### ISSUE TITLE
Suggestion to rephrase paragraph

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-io#37]
I would suggest changing

"rml:null describes which data values inside the source should be considered as NULL. Defaults to the default NULL character if available. If none is available such as CSV, no values are considered NULL, unless specified. Example: CSV does not have a default NULL character, so no value is considered NULL. However, JSON has a NULL character specified: null, this one is used together with the ones specified through rml:null."

to 

"`rml:null` indicate which data values inside the source should be considered as NULL values. The value for this predicate defaults to the default NULL token of the underlying data model (e.g., `NULL` in relational databases and `null` in JSON) and are always processed as such. Some data models have no such default NULL token, such as CSV. When that is the case, then the empty string ϵ is considered NULL."

I understood that one can declare multiple rml:null, but that the default NULL token is always used. How would one otherwise try to process these NULL tokens. The problem, however, is with the phrasing of "unless specified" for CSV files. That gives the impression that rml:null can be "overwritten" for CSV. Is ϵ always considered rml:null? If yes, then we can posit it as such. If not, then this probably needs a section with examples.

**Comment by DylanVanAssche** [comment]
Thanks for the suggestion!

The reason we have it like this is because in some datasets empty strings have actually meaning differently from a NULL value.
That's why we have only the default data model builtin NULL values as always and otherwise we assume everything is a good value. For CSV, you can have almost everything as NULL values, things I have seen:

- `NULL`
- `null`
- `\N`
- ` ` (empty cell)
- ...

I see your remark about overriding, that ain't possible for the default ones like `NULL` in RDBs and `null` in JSON.
What do you think we should do here? because `When that is the case, then the empty string ϵ is considered NULL.` is something we cannot enforce by default IMO.

**Comment by chrdebru** [comment]
The problem is that, depending on the reference formulation, extra rml:null properties "behave" differently:

RDB (default NULL) -> rml:null "foo" will result in {NULL, "foo"} as null values.
CSV (default ϵ) -> no additional rml:null " foo", then {ϵ} as null values.
CSV (default ϵ) -> rml:null "foo" will result in {"foo"} as null values.

Because of that difference in behavior, it will need to be documented for all reference formulations without a NULL token. This could be solved with some sort of seperate paragraph (e.g., a "warning" ).

**Comment by DylanVanAssche** [comment]
Ah I see what you mean, we need some examples to make it more clear that it is a combination of the builtin ones for a reference formulation + the ones defined by `rml:null`.
