### ISSUE TITLE
LogicalTarget to Revise

### ISSUE THREAD

**Issue by tirrolo** [kg-construct/rml-io#43]
Section 8 of the document is quite verbose, mostly redundant, and as a result it contains errors due to copy-paste. 

For instance, the output of Example in 8.4 is wrong:

~~~
# file:///data/dump1.nt
<http://example.org/0> <http://xmlns.com/foaf/0.1/name> "Kara Danvers" .
<http://example.org/1> <http://xmlns.com/foaf/0.1/name> "Alex Danvers" .
<http://example.org/2> <http://xmlns.com/foaf/0.1/name> "J'onn J'onzz" .
<http://example.org/3> <http://xmlns.com/foaf/0.1/name> "Nia Nal" .

# file:///data/dump2.nt
<http://example.org/0> <http://xmlns.com/foaf/0.1/name> "Kara Danvers" .
<http://example.org/1> <http://xmlns.com/foaf/0.1/name> "Alex Danvers" .
<http://example.org/2> <http://xmlns.com/foaf/0.1/name> "J'onn J'onzz" .
<http://example.org/3> <http://xmlns.com/foaf/0.1/name> "Nia Nal" .
~~~

Note that the second group of triples should refer to nicknames instead.
  
Is it really necessary to provide all possible examples? Is there a general rule on how this works, that we could write instead?

**Comment by DylanVanAssche** [comment]
> Note that the second group of triples should refer to nicknames instead.

Will have a look, thanks for spotting this!

> Is it really necessary to provide all possible examples?

For me, most specs need way more examples, RML-IO has many of them for Logical Targets.
Some of them could be reduced, but all combinations that can be done are specified in the spec.
Without an example, it can be tricky, but we could reduce the verbosity to the bare essentials instead of a full example.

> Is there a general rule on how this works, that we could write instead?

The general rule is that you need to output a quad to a Logical Target if the generation of the quad has a Logical Target specified in any of the Term Maps. It is mentioned here:

_A Term Map MAY also contain zero or more rml:logicalTarget properties to export all triples containing the generated term to different targets. The same Term Map can have multiple targets by specifying multiple rml:logicalTarget properties in the Term Map._

**Comment by tirrolo** [comment]
Dear Dylan, thanks for the reply.

The sentence is a bit obscure to us and also imprecise. For instance, it is not clear what "export all triples containing the generated term" actually means (overall? Locally to the triples map?).

We would propose the following refactoring (not sure how to integrate within the full text of Sec. 6):

_Each RML processor has a default target where generated triples are exported. Logical Targets provide a mechanism to override this default target for some of the triples to be exported._

_Logical Targets are defined in Term Maps. A Term Map MAY contain zero or more `rml:logicalTarget` properties to export all triples containing the generated term to different targets. Specifically, when generating a triple `t`, if any of the term maps involved in the generation of `t` contains a logical target `LT`, then triple `t` exported to target `LT`. If none of those Term Maps contains a Logical Target, then the triple `t` is sent to the default target of the processor._

**Comment by DylanVanAssche** [comment]
Thanks for the suggestion! That's exactly what happens.
Although we should use quads I think because a GraphMap is also a Term Map.
