### ISSUE TITLE
remove obsolete spec and links to it

### ISSUE THREAD

**Issue by VladimirAlexiev** [kg-construct/rml-io#64]
This repo lists the official spec location as http://w3id.org/rml/io/spec/, which redirects to https://kg-construct.github.io/rml-io/spec/docs/.

But https://rml.io/docs/rml/tutorials/target/ refers to https://rml.io/specs/dataio/, which seems obsolete.
Please delete the obsolete spec, and fix the links in the tutorial.
Thanks!

**Comment by DylanVanAssche** [comment]
This repository lists officially that the spec is located at http://w3id.org/rml/io/spec/
This is the W3C Community Group specification that is being developed.

> But https://rml.io/docs/rml/tutorials/target/ refers to https://rml.io/specs/dataio/, which seems obsolete.
Please delete the obsolete spec, and fix the links in the tutorial.

We cannot change this currently because:

1. The tutorial is still applicable to the tools developed by the rml.io team
2. The old specs there are used by the current tools and are referenced in scientific papers

What could be done is mentioning some kind of deprecation and pointing to the new W3C Community Group specifications when the tools catch up with the new specifications which should be rather soon thanks to the Challenge at the Knowledge Graph Construction Workshop ESCW 2024.

**Comment by VladimirAlexiev** [comment]
> mentioning some kind of deprecation

Yes! If I google "rml spec" it sends me to rml.io, and there are many obsolete specs there.
So it would be great to show a fat red banner, with a redirect to the respective current spec.

Also, rml.io should have another banner pointing to https://kg-construct.github.io/rml-resources/portal/index.html

@andimou, @bjdmeest could you guys do this?

**Comment by DylanVanAssche** [comment]
We can arrange that :) No problem!

**Comment by DylanVanAssche** [comment]
Fixed. Thanks!
